DROP TABLE IF EXISTS ORDER_CODE;
DROP TABLE IF EXISTS ORDER_CODE_DETAILS;

CREATE TABLE ORDER_CODE (
    ORDER_NUMBER INTEGER PRIMARY KEY,
    LEVEL int NOT NULL ,
    CODE varchar(5) NOT NULL ,
    PARENT varchar(10) NULL,
    DESCRIPTION varchar(100) NOT NULL
);

CREATE TABLE ORDER_CODE_DETAILS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_INCLUDE varchar(500) NULL,
    ADDITIONAL_ITEM_INCLUDE varchar(100) NULL,
    RULINGS varchar(100) NULL,
    ITEM_EXCLUDE varchar(500) NULL,
    REFERENCE_TO_ISIC char NULL,
    ORDER_NUMBER INT,
    foreign key (ORDER_NUMBER) references ORDER_CODE(ORDER_NUMBER)
);